name: tarab_ai
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.6.0
      - ace-step==0.2.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.1.0
      - blis==1.3.3
      - brotli==1.2.0
      - catalogue==2.0.10
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpathlib==0.23.0
      - colorama==0.4.6
      - confection==0.1.5
      - contourpy==1.3.2
      - cutlet==0.5.0
      - cycler==0.12.1
      - cymem==2.0.13
      - datasets==3.4.1
      - decorator==5.2.1
      - diffusers==0.36.0
      - dill==0.3.8
      - docopt==0.6.2
      - exceptiongroup==1.3.1
      - fastapi==0.128.0
      - ffmpy==1.0.0
      - filelock==3.20.0
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2024.12.0
      - fugashi==1.5.2
      - gradio==5.50.0
      - gradio-client==1.14.0
      - groovy==0.1.2
      - grpcio==1.76.0
      - h11==0.16.0
      - hangul-romanize==0.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - jaconv==0.4.1
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - langcodes==3.5.1
      - lazy-loader==0.4
      - librosa==0.11.0
      - lightning-utilities==0.15.2
      - llvmlite==0.46.0
      - loguru==0.7.3
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mojimoji==0.0.13
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.16
      - murmurhash==1.0.15
      - networkx==3.4.2
      - num2words==0.5.14
      - numba==0.63.1
      - numpy==2.2.6
      - orjson==3.11.5
      - packaging==25.0
      - pandas==2.3.3
      - peft==0.17.1
      - pillow==10.4.0
      - platformdirs==4.5.1
      - pooch==1.8.2
      - preshed==3.0.12
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.2.1
      - py3langid==0.3.0
      - pyarrow==22.0.0
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pypinyin==0.53.0
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.21
      - pytorch-lightning==2.5.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - ruff==0.14.10
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.5.0
      - soundfile==0.13.1
      - soxr==1.0.0
      - spacy==3.8.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.2
      - starlette==0.50.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - thinc==8.3.10
      - threadpoolctl==3.6.0
      - tokenizers==0.21.4
      - tomlkit==0.12.0
      - torch==2.9.1+cu130
      - torchaudio==2.9.1+cu130
      - torchmetrics==1.8.2
      - torchvision==0.24.1+cu130
      - tqdm==4.67.1
      - transformers==4.50.0
      - typer==0.21.0
      - typer-slim==0.21.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - unidic-lite==1.0.8
      - urllib3==2.6.2
      - uvicorn==0.40.0
      - wasabi==1.1.3
      - weasel==0.4.3
      - websockets==15.0.1
      - werkzeug==3.1.4
      - win32-setctime==1.2.0
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: C:\Users\Abdoo\miniconda3\envs\tarab_ai
